# Generated by Django 4.2.4 on 2024-02-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
